# Generated by Django 4.2.10 on 2025-10-26 14:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('graphs', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='temp',
            name='camada',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='temp',
            name='memoria',
            field=models.IntegerField(null=True),
        ),
    ]
