# Generated by Django 4.2.10 on 2025-11-03 19:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('graphs', '0002_temp_camada_temp_memoria'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Temp',
        ),
    ]
