# Generated by Django 4.2.10 on 2025-11-27 23:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('temps', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='temp',
            name='nome',
            field=models.CharField(max_length=15, null=True),
        ),
        migrations.AddField(
            model_name='temp',
            name='peso',
            field=models.DecimalField(decimal_places=2, max_digits=5, null=True),
        ),
    ]
